version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests with docker-compose
          command: docker-compose -f compose-test-ci.yml run test

  deploy:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t thierno9/iot-api:$CIRCLE_BRANCH .
      - run:
          name: Tag image with commit SHA
          command: docker tag thierno9/iot-api:$CIRCLE_BRANCH thierno9/iot-api:$CIRCLE_SHA1
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Push images
          command: |
            docker push thierno9/iot-api:$CIRCLE_BRANCH
            docker push thierno9/iot-api:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
